name: ocr_scan_text
description: OCR Scan Text is a wrapper around the "Google ML kit Text Recognition" library.
version: 2.0.0
homepage: https://github.com/boursorama/ocr_scan_text

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  google_mlkit_text_recognition: ^0.15.0
  camera: ^0.11.2
  image: ^4.5.4
  pdfrx: ^2.1.3
  path: ^1.9.1
  path_provider: ^2.1.5
  file_picker: ^8.1.4
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.boursorama.ocr_scan_text.ocr_scan_text
        pluginClass: OcrScanTextPlugin
      ios:
        pluginClass: OcrScanTextPlugin
